package-lock.json, package.json, src/app.ts, src/helpers/contentTypeMap.json, src/helpers/extraBindings/io.ts, ui/src/components/Certificator.jsx
Start implementing the API's that the UI depends on
=> UI api wip

doSampleResources.txt, maps/doExtractGender.txt, maps/doSampleResources.txt
Periodical PR with different updates ... see commits
=> Periodical PR

maps/doExtractGender.txt, maps/doExtractidentifiers.txt, maps/doGetMetadata.txt, maps/isCapstatValidationSuccess.txt, maps/isMetaDataHttp200.txt, maps/isMetadataContentTypeOk.txt, maps/isMetadataResourceTypeOk.txt, maps/isSearchModiferOk.txt
updated map status to in-progress & merged branches due to committing before pulling
=> Misc2at25-09

package-lock.json, package.json, src/app.ts, src/engine.ts, src/helpers/expressions.ts, src/setup.ts
$fhirSever returns the base URL of the FHIR server configured in .env
=> Add $fhirSever parameter

maps/mockAction10e.txt, maps/mockAction10f.txt, maps/mockAction10s.txt, maps/mockAction1e.txt, maps/mockAction1f.txt, maps/mockAction1s.txt, src/app.ts, src/engine.ts, src/helpers/expressions.ts
* Added mock action maps for use in a mock kit
* Added env variable **MOCKING_KIT**. If set to true, the mock kit will be exposed as part of the kits tree. Otherwise it's hidden
* Added env variable **RESOURCE_SAMPLE_SIZE**. Setting this will override the default sample size (currently set to 1000)
* Added parameter binding for **$sampleSize**. This is a static parameter that can be used in any mapping, and will contain the currently configured sample size
* fixed issues related to running kits without any skipped tests
* fixed issues related to status tracking during kit runs
=> Fix running issues + mock kit + new env variables

kits.json, maps/doSampleResources.txt, maps/doSampleWrapper.txt, maps/doSamplingInput.txt, maps/extractCapabilityStatementResource.txt, maps/mockAction10e.txt, report/src/components/TableChart.jsx, src/app.ts, src/engine.ts, src/helpers/expressions.ts, src/helpers/getSampleSize.ts, src/helpers/serveUiFiles.ts
* fixed issues with resource sampling
* finalize report charts for mvp
=> Serve report data

src/helpers/expressions.ts
update chart (id=identifier-chart) to show only patient data
=> fix: update chart 'id': 'identifier-chart' to show only patient data

kits.json, maps/doSuccessfulReadResponse.txt, maps/isReadId.txt
Create Test 87 artifacts and some updates to doSuccessfulReadResponse to support Test 87 (writing to disk of relevant GET params)
=> feat: Test 87

.gitignore, kits.json, maps/doCountResources.txt, maps/doExtractIds.txt, maps/idRegexMatch.txt, maps/isReadHasId.txt, maps/isReadId.txt
Create and fix bugs related to Tests 26 & 29 and a small upgrade to test 31
=> Test26and29

src/helpers/expressions.ts
Fix display bug caused by missing UI defenitons
=> fix: Test31 disply fix

kits.json, maps/isDuplicateIds.txt, src/helpers/expressions.ts
Added test28 + TestID attribute to the "Run Summary" table
=> feat: Test28

kits.json, maps/doSuccessfulSearch.txt, maps/isSuccessfulSearchBundle.txt, maps/isSuccessfulSearchCode.txt
Changes in various files related to adding some search tests
=> feat: add search tests

maps/doExtractGender.txt, maps/extractCapabilityStatementResource.txt
=> Fix $doGetMetadata & $doExtractGender

kits.json, maps/doExtractEncounterClass.txt
Added the extraction map & updated the kits.json to expose test in UI
=> feat: Encounter class distribution test

src/helpers/expressions.ts
Configure reports to show test59 results
=> feat: expose test 59 in UI

kits.json, maps/doExtractEncounterType.txt, src/helpers/expressions.ts
Commit **8289610** Test 64: contains new mapping doExtractEncounterType and update in kits.json. 
Commit **23bdde0** Test 64: contains update in expressions.ts to present Test 64 report.
=> feat(Test 64)

kits.json, maps/doExtractConditionRecordedDate.txt, src/helpers/expressions.ts
Added Test 174
https://app.clickup.com/t/8698c6y17
=> feat(Test 174)

src/helpers/expressions.ts
https://app.clickup.com/t/8698funkx
https://app.clickup.com/t/8698funft
=> fix(Test 68),  fix(Test 174)

ManageKits.md
=> feat: document kits.json usage

maps/doSamplingInput.txt, src/helpers/expressions.ts
https://github.com/8400TheHealthNetwork/certificator/issues/131
https://app.clickup.com/t/8698ntuq2
Fixed logic in doSamplingInput.txt: When the RESOURCE_SAMPLE_SIZE variable (located in the .env file) is undefined or set to 0, the amountToCollect for each resource is now sourced from infoBinsDistinct.json.
=> fix(User defined sample size not used)

kits.json, maps/isEndpointAvailable.txt
New test - created corresponding mapping file and modified kits.json file
=> feat(Test 210)

kits.json, maps/isPatientEndpointAvailable.txt
Modified the test name/description/mapper to reflect the actual endpoint - Patient
=> fix(Test 210)

kits.json, maps/doCheckPatientHasOfficialId.txt, maps/doInfoBinsDistinct.txt, src/helpers/expressions.ts
something went wrong in the previous PR for this test. After fetching main I realized the test is still not there, so I created this new PR
=> Feature/test271 retry PR
